### ISSUE TITLE
Mensaje "micro;bit not identified in drive C:\."

### ISSUE THREAD

**Issue by ngammarano** [DevelopGoldsword/micro-phone#2]
Al hacer click en "Copy", aparece un mensaje diciendo "micro;bit not identified in drive C:\.".
Adjunto captura de pantalla.
Sin embargo, al darle "Aceptar" a dicho mensaje, se copia correctamente el programa a la micro:bit.

![micro;phone_screenshot](https://user-images.githubusercontent.com/54072413/68309905-eaecd600-008d-11ea-9221-54c36e412b2c.png)

**Comment by DevelopGoldsword** [comment]
That is normal. To make this compatible with Linux, I had to use a loop that goes through each of the drives. I will look into an alternative that has much less pop-ups.
